### PR TITLE
delete this

### PR DESCRIPTION
**Pull request by forkiesassds**

### CODE REVIEW

**Comment by PF94** [comment]
guess what they're not going to do it because you know who neglects retrosite

XPuser

**Comment by PF94** [comment]
@TLWXPUser do it you kicked icty off retrosite and you're still keeping his fucking subsite he can't access

btw i'm making a video about why both retrosite and 2003page is useless LOL

**Comment by PF94** [comment]
still not pulled

retrosite won't survive in 2021

**Comment by forkiesassds** [comment]
you just want to keep my crap because you want to make people think there is a lot of content here...

**Comment by JarHead4** [comment]
> 
> 
> you just want to keep my crap because you want to make people think there is a lot of content here...

i'll be honest i completely forgot to remove your subsite, here i'll do it right now

**Pull request closed without merging**
